# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto  # Use current coverage as baseline
        threshold: 10%  # Allow significant decrease
        
    patch:
      default:
        target: 0%  # No coverage requirement for new code
        informational: true  # Don't fail the build

comment:
  # Configure how Codecov comments on PRs
  layout: "header,reach,diff,flags,tree,files"  # Include header with links and file-level coverage details
  behavior: default              # Update existing comment instead of creating new ones
  require_changes: true           # Only comment when coverage changes (reduces noise)
  require_base: false             # Don't require base branch for comparison
  require_head: true              # Require head branch to exist
  show_carryforward_flags: true   # Display flags that carry forward from previous builds
  show_critical_paths: true       # Show files that are critical for coverage
  hide_project_coverage: false    # Show project coverage in the comment
  
# Flags removed as we're only testing with Node.js 24

# Ignore certain files from coverage
ignore:
  - "tests/**"
  - "scripts/**"
  - "dist/**"
  - "**/*.test.ts"
  - "lib/**"
  - "**/*.d.ts"
  - "node_modules/**"
  - "docs/**"
  - "coverage/**"
