name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci-push-main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint:check

      - name: Build
        run: bun run build

      - name: Check dependencies
        run: bun run knip

      - name: Test
        run: bun run test:coverage
