name: pr-auto-assign

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr-auto-assign:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/pr-auto-assign-config.yml'
